blank_issues_enabled: false
contact_links:
  - name: Ask a question or get support
    url: https://github.com/orgs/arextest/discussions
    about: Ask a question or request support for AREX community