name: Feature Request
description: Suggest an idea for this project
title: "[Feature] "
labels: [ "feature" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding the time to propose new feature!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >
        Please search to see if an issue already exists for the feature you wanted.
      options:
        - label: >
            I had searched in the [issues](https://github.com/arextest/arex-agent-java/issues) and found no similar
            issues.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.

  - type: textarea
    attributes:
      label: Solution
      description: Describe the solution you'd like.
      placeholder: >
        If you don't know how to implement this feature, then describe what you want to achieve.

  - type: textarea
    attributes:
      label: Related issues
      description: Is your feature request related to a problem or an issue? Please describe.

  - type: checkboxes
    attributes:
      label: Are you willing to submit a pull request to implement this on your own?
      description: >
        We will be happy to guide you in the contribution process especially if you already have a good understanding of how to implement the feature.
      options:
        - label: Yes I am willing to submit a pull request on my own!

  - type: markdown
    attributes:
      value: "Thanks for completing the form!"
